# Generated by Django 5.1.2 on 2024-10-12 10:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=255)),
                ('startDate', models.DateTimeField(auto_now_add=True)),
                ('endDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('budget', models.FloatField()),
                ('status', models.CharField(choices=[('NOS', 'Not Started'), ('ACT', 'Active'), ('COM', 'Completed'), ('CAN', 'Cancelled'), ('ONH', 'On Hold')], default='NOS', max_length=3)),
            ],
            options={
                'ordering': ['-startDate'],
                'indexes': [models.Index(fields=['-startDate'], name='project_pro_startDa_2948d5_idx')],
            },
        ),
    ]
